#!/bin/bash

# Test de création de design avec prix
echo "🧪 Test création design avec prix..."

# Remplacez YOUR_JWT_TOKEN par un vrai token
TOKEN="YOUR_JWT_TOKEN"

# Test avec /vendor/designs (JSON)
echo "📡 Test POST /vendor/designs avec prix..."
curl -X POST "http://localhost:3004/vendor/designs" \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $TOKEN" \
  -d '{
    "name": "TEST PRIX",
    "description": "Test pour vérifier le prix", 
    "price": 5000,
    "category": "LOGO",
    "imageBase64": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8/x8OAAMCAQMBAQEBAQEBAQEBAQEBAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA="
  }' \
  | jq '.'

echo ""
echo "🔍 Vérification des designs créés..."
curl -X GET "http://localhost:3004/api/designs?page=1&limit=1&sortBy=createdAt" \
  -H "accept: application/json" \
  | jq '.data.designs[0] | {id, name, price, createdAt}'